#!/bin/sh
pidof i3lock > /dev/null 2>&1 || {
	which xlock-precommand > /dev/null 2>&1 && xlock-precommand
	xset dpms 30 30 30
	i3lock -n -i $HOME/.locked.png -f -c 000000
	xset -dpms
	which xlock-postcommand > /dev/null 2>&1 && xlock-postcommand
}

